HEYDOC/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vaccination_info/', include('vaccination_info.urls')),
    path('consultation/', include('consultation.urls')),
    path('covid_drug_recommendations/', include('covid_drug_recommendations.urls')),
    path('article/', include('article.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('buy/', include('buy.urls')),
    path('homepage/', include('homepage.urls')),
]



urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views
import article
app_name = 'article'
urlpatterns = [
    path('', views.index, name='artikel'), 
    path('getArticles', views.getArticles, name='getArticles'),
    path('create', views.create, name='create'),
    path('news', views.article, name= 'article'),
    path('datas', views.getItem, name= 'datas'),
    path('addArticle', views.addItem, name= 'addArticle'), 
]

buy/urls.py
from django.urls import path
from .views import HomeView, getItem, product_detail, item_list, add_to_cart, remove_from_cart,add, OrderSummaryView, remove_single_item_from_cart, search_item, categorised_item, getItem, getOrderItem, getOrder
urlpatterns = [
    path('', HomeView.as_view(), name = 'index'),
    path('product', OrderSummaryView.as_view(), name = 'product'),
    path('item', item_list, name = 'item_list'),
    path('add-to-cart/<slug>/', add_to_cart, name  ='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name = "remove-from-cart"),
    path('add',add,name = "add"),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('search',search_item, name = 'search'),
    path('category/<str:value>/', categorised_item, name = 'category'),
    path('category/all/add', add, name = "add"),
    path('category/C/add', add, name = "add"),
    path('category/A/add', add, name = "add"),
    path('category/H/add', add, name = "add"),
    path('category/V/add', add, name = "add"),
    path('category/F/add', add, name = "add"),
    path('category/S/add', add, name = "add"),
    path('category/I/add', add, name = "add"),
    path('category/D/add', add, name = "add"),
    path('category/O/add', add, name = "add"),
    path('datas/item/', getItem),
    path('datas/orderitem/', getOrderItem),
    path('datas/order/', getOrder),



]

article/models.py
from django.db import models
from django.utils.timezone import now

class Article(models.Model):
    title = models.TextField()
    article = models.TextField()
    source = models.TextField()
    datetime = models.DateTimeField(default=now)
    

article/forms.py
from django.db.models import fields
from .models import Article
from django import forms

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

article/views.py
import json
from typing import List
from django.http.response import HttpResponse, HttpResponseRedirectBase
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .forms import ArticleForm
from .models import Article
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializer import *


# Create your views here.
def index(request): 
    return render(request, 'form_article.html')

def getArticles(request):
    articles = Article.objects.all()
    return JsonResponse({"articles":list(articles.values())})

def create(request):
    if request.method == 'POST':
        title = request.POST['title']    
        article = request.POST['article']   
        source = request.POST['source']  
        

        new_articles = Article(title=title, article=article, source=source)
        new_articles.save()
        return HttpResponse('New Articles Created Successfully')

def article(request):
    article = Article.objects.all()
    return render(request, 'article.html', {'article':article})     


@api_view(['GET'])
def getItem(request):
    items = Article.objects.all()
    serializer = ItemSerializer(items, many = True)
    return Response(serializer.data)

@csrf_exempt
def addItem(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        title_flutter = data['title']
        article_flutter = data['article']
        source_flutter = data['source']
        

        article_form = Article(title = title_flutter, article = article_flutter, source = source_flutter)

        
        article_form.save()
        return JsonResponse ({"status": "success"}, status = 200)

    
    else:    
        return JsonResponse ({"status": "error"}, status = 401)

article/templates/article.html
<!DOCTYPE html>
<html lang="en">
<style>
    body{
        overflow-x: hidden;
    }
    .card {
      width: auto;
      background: black;
      box-shadow: 0 0 15px;
      height: 500px;
      margin: auto;
    }
    .card img{
        width: 100%;
        height: 30%;
        border-radius: 10px 10px 0 0;
    }
    .card-body{
        padding: 10px 20px;
    }

    .card-body button{
        outline: none;
        padding: 10px 15px;
        font-weight: bold;
    }

    #article_box {
        height: 40px;
    }

    .container {
        margin-bottom: 200px;
    }
    
</style>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Dosis' rel='stylesheet'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>News</title>
</head>
{% include 'navbarhomepage.html' %}
<body>
    
    {% block content %}
    <div style="margin-left:50px; padding-bottom: 20px; padding-top: 60px;"> <a href="{% url 'article:artikel' %}" style="color:black" >&lt Back to Form</a></div>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
        {% if article %}
        {% for i in article %}
        <div class="col">
          <div class="container text-black" style="width: 20rem;">
              <div class="card">
                <img src="https://cdn-2.tstatic.net/tribunnews/foto/bank/images/update-covid-19-update-corona-update-virus-corona-ilustrasi-update.jpg" alt="https://kkpambon.com/wp-content/uploads/2015/03/banner.png">
                  <div class="card-header">
                      {{ i.title }}
                  </div>
                  <div class="card-body">
                      <p class="card-text">{{i.article|truncatechars:100}} </p>
                      <h5 class="card-text"> {{i.source|truncatechars:30}} </h5>
                  </div>
                  <div class="card-footer">
                    <a href="{{ i.source }}">Read More</a>
                    <small>{{ i.datetime }}</small>
                  </div>
                  
              </div>
              <div class="text-center">
              </div>
          </div>
      </div>
      {% endfor %}
      {% endif %}
  </div>
  
  {% endblock %}   
</body>
<script src="https://code.jquery.com/jquery-3.2.1.min.js%22%3E"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% include 'footer.html' %}

</html>

article/templates/form_article.html
<!DOCTYPE html>
<html lang="en">
  <style>
    body{
      
      margin: 0;
    }
    /* h1{
          text-width: bolder !important;
          font-size: 75px;
          text-align: center;
          font-family: Dosis;
          padding-top: 270px;
  
      } */
  
      form {
          width: 25%;
          text-align: center;
          margin-left: auto;
          margin-right: auto;
          font-family: Dosis;
          margin-top: 190px;
          margin-bottom: 243px;
      }
  
      #article {
          height: 150px;
          
          
      }
      .form-control{
          font-family: Dosis;
          border-radius: 80px;
          font-size: 24px;
      }
  
      .button {
          border-radius: 80px;
          border: none;
          font-size: 24px;
          padding: 2px 20px;
          margin : -10px 10px;
          transition-duration: 0.4s;
          cursor: pointer;
      }
  
      #button1 {
          background-color: #00ADB5;
      }
  
  
      #button1:hover {
          background-color: #4CAF50;
          color: white;
      }
  
      #button2:hover {
          background-color: #f44336;
          color: white;
      }
      .submissionfield { width: 90px; height: 390px; border: 1px solid #999999; padding: 5px; }
  </style>
  
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Article</title>
</head>
{% include 'navbarhomepage.html' %}
<body>
  {% block content %}
  <div class="cointer">
    <form method="POST" id="post-form"> 
      <h1>Submit Form</h1>
      {% csrf_token %}
      <div class="form-group">
          <div class="col">
              <input type="text" class="form-control" placeholder="Title" name="title" id="title"><br>
          </div>
          <div class="col" style="margin-bottom: 15px;">
            <textarea cols="40" rows="20" placeholder="Type article here" class = "form-control add-form" name="article" id="article"></textarea>
        </div>
          <div class="col">
            <input type="url" class="form-control" placeholder="Source " name="source" id="source"><br>
          </div>
          
      </div>
      <input type ="submit" class="button" id="button1" value="Submit">
      <input type="reset" class="button" id="button2" value="Clear" href="/">
      </form>
  </div>
  
  
{% endblock %}  

</body>
<footer>
  {% include 'footer.html' %}
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.min.js%22%3E"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>
$(document).on('submit','#post-form',function(e) {
  e.preventDefault();

    $.ajax({
      type:'POST',
      url: "create",
      data:{
        title:$('#title').val(),
        article:$('#article').val(),
        source:$('#source').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function (response) {
        alert("Updated");
      },  
    });
});
   
  
</script>
</html>